### ISSUE TITLE
Rich text transformer fails with complex list

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/rich-text-resolver-js#24]
### Brief bug description

If you try to parser the table with list, it fails with error:

```plain
TypeError: Cannot read properties of undefined (reading 'push')

      142 |         if (item._type === 'cell') {
      143 |             const tableRow = mergedItems.pop() as IPortableTextTableRow;
    > 144 |             tableRow.cells.push(item);
          |                            ^
      145 |             mergedItems.push(tableRow);
      146 |         } else {
      147 |             mergedItems.push(item);

      at src/transformers/portable-text-transformer/portable-text-transformer.ts:144:28
          at Array.reduce (<anonymous>)
      at mergeRowsAndCells (src/transformers/portable-text-transformer/portable-text-transformer.ts:141:38)
      at src/utils/transformer-utils.ts:158:84
      at src/utils/transformer-utils.ts:158:67
      at src/utils/transformer-utils.ts:158:67
      at src/utils/transformer-utils.ts:158:67
      at transformToPortableText (src/transformers/portable-text-transformer/portable-text-transformer.ts:57:12)
      at Object.<anonymous> (tests/transfomers/portable-text-transformer/portable-text-transformer.spec.ts:144:43)
```

### Expected behavior

Do not fail

### Test environment

- Platform/OS: [e.g. .NET Core 2.1, iOS]

### Additional context

YOu can start with https://github.com/kontent-ai/rich-text-resolver-js/tree/tables-with-list-issue branch, that already contains a failing test - just run `npm run test -- -u` (to generate a snapshot if succeed) and you get an error in  `portable text transformer › Transform table with everything in it`

**Comment by pokornyd** [comment]
Was slightly more problematic as I uncovered couple different bugs along the way. The sheer number of combinations makes it hard to cover all edge cases, we may yet find similar issues in the future.
